language: python
python: 2.7
sudo: false
cache:
    - pip
env:
    - TOXENV=py26-16
    - TOXENV=py27-16
    - TOXENV=py27-17
    - TOXENV=py27-18
    - TOXENV=py27-19
    - TOXENV=pypy-16
    - TOXENV=pypy-17
    - TOXENV=pypy-18
    - TOXENV=pypy-19
install:
    - pip install tox
script:
    - tox
